apiVersion: v1
kind: ConfigMap
metadata:
  name: numaplane-controller-config
  namespace: numaplane-system
data:
  config.yaml: |
    clusterName: "example-cluster"
    timeIntervalSec: 60
    repoCredentials:
      https://bitbucket.org/numaplane:
        HTTPCredential:
          Username: "exampleUser"
          Password:
            name: "http-creds"
            key: "password"
      https://gitlab.org/numaplane:
        SSHCredential:
          SSHKey:
            name: "ssh-creds"
            key: "sshKey"
      https://github.org/numaplane:
        TLS:
          insecureSkipVerify: true
          CACertSecret:
            name: "ca-cert-secret"
            key: "ca.crt"
          CertSecret:
            name: "cert-secret"
            key: "tls.crt"
          KeySecret:
            name: "key-secret"
            key: "tls.key"
