apiVersion: v1
kind: ConfigMap
metadata:
  name: numaplane-controller-config
  namespace: numaplane-system
data:
  config.yaml: |
    clusterName: "example-cluster"
    timeIntervalSec: 60
    repoCredentials:
      "https://github.com/rustyTest/testprivateRepo":
        HTTPCredential:
          Username: "exampleUser"
          Password:
            name: "http-creds"
            key: "password"
      "git@github.com:rustyTest/testprivateRepo.git":
        SSHCredential:
          SSHKey:
            name: "ssh-creds"
            key: "sshKey"
      
