apiVersion: v1
kind: ConfigMap
metadata:
  name: numaplane-controller-config
  namespace: numaplane-system
data:
  config.yaml: |
    clusterName: "my-cluster"
    timeInterval: 5
    repoCredentials:
      "testGit":
          secretKeyRef:
            key: secret-basic-auth
       
