#Example config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: numaplane-system
data:
  config.yaml: |
    timeIntervalSec: 60
    repoCredentials:
    - url: "github.com/numaproj-labs"
      httpCredential:
        username: "exampleUser"
        password:
          name: "http-creds"
          key: "password"
    - url: "github.com:numaproj"
      sshCredential:
        SSHKey:
          name: "ssh-creds"
          key: "sshKey"
      tls:
        insecureSkipVerify: true
    - url: "github.com/numalabs"
      httpCredential:
        username: "exampleuser3"
        password:
          name: "http-creds"
          key: "password"
      tls:
        insecureSkipVerify: true

