apiVersion: v1
kind: ConfigMap
metadata:
  name: numaplane-controller-config
  namespace: system
data:
  config.yaml: |
    clusterName: "numaplanecluster"
    timeInterval: "3m"
    repositoryPathPrefix: "{}"