apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: numaplane-system
data:
  config.yaml: |
    clusterName: CLUSTER_NAME_VALUE # Replace with the cluster name where numaplane will get deployed.
    timeIntervalSec: 60
