apiVersion: v1
kind: ConfigMap
metadata:
  name: numaplane-controller-config
  namespace: numaplane-system
data:
  config.yaml: |
    clusterName: "staging-usw2-k8s"
    timeInterval: 5
    repoCredentials:
      "https://github.com/xdevxy/numaflow-example-pipelines.git":
            name: secret-name
            key: secret-basic-auth
       
