#Example config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: numaplane-controller-config
data:
  config.yaml: |
    syncTimeIntervalMs: 30000
    includedResources: "group=apps,kind=Deployment;\
    group=,kind=ConfigMap;group=,kind=Secret;group=,kind=ServiceAccount;\
    group=numaflow.numaproj.io,kind=;\
    group=numaflow.numaproj.io,kind=;\
    group=rbac.authorization.k8s.io,kind=RoleBinding;group=rbac.authorization.k8s.io,kind=Role"
