apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- controller-manager.yaml
- controller-config.yaml

images:
- name: quay.io/numaproj/numaplane-controller
  newTag: v0.1.0-beta.3
