apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- controller-manager.yaml
- controller-config.yaml
- persistent-volume.yaml
- persistent-volume-claim.yaml
#- storageclass.yaml
#- pvc-efs.yaml

images:
- name: quay.io/numaproj/numaplane-controller
  newTag: latest
