apiVersion: v1
kind: PersistentVolume
metadata:
  name: numaplane-repo-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/tmp"
