# permissions for end users to view gitsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitsync-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: numaplane
    app.kubernetes.io/part-of: numaplane
    app.kubernetes.io/managed-by: kustomize
  name: gitsync-viewer-role
rules:
- apiGroups:
  - numaplane.numaproj.io
  resources:
  - gitsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - numaplane.numaproj.io
  resources:
  - gitsyncs/status
  verbs:
  - get
