# permissions for end users to view isbservicerollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: numaplane
    app.kubernetes.io/managed-by: kustomize
  name: isbservicerollout-viewer-role
rules:
- apiGroups:
  - numaplane.numaproj.io.github.com.numaproj-labs
  resources:
  - isbservicerollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - numaplane.numaproj.io.github.com.numaproj-labs
  resources:
  - isbservicerollouts/status
  verbs:
  - get
