apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- numaplane-aggregate-to-admin.yaml
- numaplane-aggregate-to-edit.yaml
- numaplane-aggregate-to-view.yaml
