apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: numaplane
  name: numaplane-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: numaplane-leader-election-role
subjects:
- kind: ServiceAccount
  name: numaplane-sa
