# permissions for end users to view gitsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: numaplane
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: numaplane-aggregate-to-view
rules:
- apiGroups:
  - numaplane.numaproj.io
  resources:
  - gitsyncs
  - gitsyncs/finalizer
  - gitsyncs/status
  verbs:
  - get
  - list
  - watch
