# permissions for end users to edit numaflowcontrollerrollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: numaplane
    app.kubernetes.io/managed-by: kustomize
  name: numaflowcontrollerrollout-editor-role
rules:
- apiGroups:
  - numaplane.numaproj.io.github.com.numaproj-labs
  resources:
  - numaflowcontrollerrollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - numaplane.numaproj.io.github.com.numaproj-labs
  resources:
  - numaflowcontrollerrollouts/status
  verbs:
  - get
