# permissions for end users to view pipelinerollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: numaplane
    app.kubernetes.io/managed-by: kustomize
  name: pipelinerollout-viewer-role
rules:
- apiGroups:
  - numaplane.numaproj.io
  resources:
  - pipelinerollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - numaplane.numaproj.io
  resources:
  - pipelinerollouts/status
  verbs:
  - get
