# permissions for end users to edit pipelinerollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: numaplane
    app.kubernetes.io/managed-by: kustomize
  name: pipelinerollout-editor-role
rules:
- apiGroups:
  - numaplane.numaproj.io.github.com.numaproj-labs
  resources:
  - pipelinerollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - numaplane.numaproj.io.github.com.numaproj-labs
  resources:
  - pipelinerollouts/status
  verbs:
  - get
