---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: numaplane-role
rules:
- apiGroups: ["numaflow.numaproj.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["numaplane.numaproj.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources:
    - configmaps
    - serviceaccounts
  verbs:
    - '*'
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - rolebindings
    - roles
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - secrets
    - namespaces
  verbs:
    - 'get'
    - 'list'
    - 'watch'
- apiGroups: ["apps"]
  resources:
    - deployments
  verbs:
    - '*'
