#Example config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: numaplane-controller-config
  namespace: numaplane-system
data:
  config.yaml: |
    clusterName: "CLUSTER_NAME_VALUE" # Replace with the cluster name where numaplane will get deployed.
    syncTimeIntervalMs: 30000
    autoHealEnabled: true
    cascadeDeletion: false
    repoCredentials:
      - url: "github.com/numaproj-labs"
        httpCredential:
          username: "exampleUser"
          password:
            fromKubernetesSecret:
              name: "http-creds"
              key: "password"
              namespace: "numaplane-system"  # namespace where the secrets live 
      - url: "github.com:numaproj"
        sshCredential:
          SSHKey:
            fromKubernetesSecret:
              name: "ssh-creds"
              key: "sshKey"
              namespace: "numaplane-system"
        tls:
          insecureSkipVerify: true
      - url: "git@github.com:numalabs"
        httpCredential:
          username: "exampleuser3"
          password:
            fromKubernetesSecret:
              name: "http-creds"
              key: "password"
        tls:
          insecureSkipVerify: true