clusterName: "example-cluster"
timeIntervalSec: 60
repoCredentials:
  - url: "github.com/rustyTest"
    credential:
      httpCredential:
        username: "exampleUser"
        password:
          name: "http-creds"
          key: "password"
      sshCredential:
        sshKey:
          name: "ssh-creds"
          key: "sshKey"
      tls:
        insecureSkipVerify: true
        caCertSecret:
          name: "ca-cert-secret"
          key: "ca.crt"
        certSecret:
          name: "cert-secret"
          key: "tls.crt"
        keySecret:
          name: "key-secret"
          key: "tls.key"
  - url: "github.com:numaproj"
    credential:
      httpCredential:
        username: "exampleuser2"
        password:
          name: "http-creds"
          key: "password"
      sshCredential:
        sshKey:
          name: "ssh-creds"
          key: "sshKey"
      tls:
        insecureSkipVerify: false
        caCertSecret:
          name: "ca-cert-secret"
          key: "ca.crt"
        certSecret:
          name: "cert-secret"
          key: "tls.crt"
        keySecret:
          name: "key-secret"
          key: "tls.key"
  - url: "github.com/numaproj"
    credential:
      httpCredential:
        username: "exampleuser3"
        password:
          name: "http-creds"
          key: "password"
      sshCredential:
        sshKey:
          name: "ssh-creds"
          key: "sshkey"
      tls:
        insecureSkipVerify: true
        caCertSecret:
          name: "ca-cert-secret"
          key: "ca.crt"
        certSecret:
          name: "cert-secret"
          key: "tls.crt"
        keySecret:
          name: "key-secret"
          key: "tls.key"
