apiVersion: numaplane.numaproj.io/v1alpha1
kind: GitSync
metadata:
  name: gitsync-example
  namespace: numaplane-system
spec:
  path: ""
  repoUrl: https://github.com/shubhamdixit863/yamlrepo
  targetRevision: main
  raw: {}
  destination:
    cluster: staging-usw2-k8s
    namespace: numaflow-pipeline