apiVersion: numaplane.numaproj.io/v1alpha1
kind: GitSync
metadata:
  labels:
    app.kubernetes.io/name: gitsync
    app.kubernetes.io/instance: gitsync-sample
    app.kubernetes.io/part-of: numaplane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: numaplane
  name: gitsync-sample
  namespace: numaplane-system
spec:
  repositoryPath:
    repoUrl: "https://github.com/numaproj/numaflow.git"
    path: "config/namespace-install"
    targetRevision: "main"
    name: numaflow
  destination:
    cluster: staging-usw2-k8s
    namespace: namespace-1
