apiVersion: numaplane.numaproj.io.github.com.numaproj-labs/v1
kind: GitSync
metadata:
  labels:
    app.kubernetes.io/name: gitsync
    app.kubernetes.io/instance: gitsync-sample
    app.kubernetes.io/part-of: numaplane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: numaplane
  name: gitsync-sample
spec:
  repositoryPaths:
    - repoUrl: "https://github.com/myrepo.git"
      path: "./numaflowResources/"
      targetRevision: "main"
      name: my-pipelines
    - repoUrl: "https://github.com/myrepo.git"
      path: "./nested/numaflowController/"
      targetRevision: "main"
      name: controller
  destinations:
    - cluster: staging-usw2-k8s
      namespace: namespace-1
      
