apiVersion: numaplane.numaproj.io/v1alpha1
kind: GitSync
metadata:
  name: gitsync-example
  namespace: numaplane-system
spec:
  path: "sample-pipeline"
  repoUrl: https://github.com/xdevxy/numaflow-example-pipelines.git
  targetRevision: main
  raw: {}
  destination:
    cluster: staging-usw2-k8s
    namespace: numaflow-pipeline