clusterName: "staging-usw2-k8s"
repoCredentials:
  - url: "https://github.com/numaproj-labs/numaplane-control-manifests.git"
    credential:
      HTTPCredential:
        Username: "exampleUser"
        Password:
          name: "http-creds"
          key: "password"