clusterName: "staging-usw2-k8s"
repoCredentials:
  - url: "github.com/numaproj-labs"
    credential:
      httpCredential:
        username: "exampleUser"
        password:
          name: "http-creds"
          key: "password"