#Example config map for Agent which includes a file reference generator
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: numaplane-system
data:
  config.yaml: |
    clusterName: staging-usw2-k8s
    timeIntervalSec: 60
    source:
      keyValueGenerator:
        reference:
          files:
            - path: default-clusters.json
              repoUrl: "https://github.com/myrepo.git"
              targetRevision: master
            - path: override-clusters.json
              repoUrl: "https://github.com/myrepo.git"
              targetRevision: master
      gitDefinition:
        path: sample-pipeline
        repoUrl: "https://github.com/mynumaplaneinstall.git"
        targetRevision: main
        helm:
          parameters:
            - name: clusterName
              value: '{{clusterName}}'
            - name: controllerHostName
              value: '{{controllerHostName}}'