name: release
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - dev-*

defaults:
  run:
    shell: bash

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    if: github.repository == 'numaproj-labs/numaplane'
    name: Build binaries
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

  build-push-linux-multi:
    name: Build & push linux/amd64 and linux/arm64
    needs: [ build-binaries ]
    runs-on: ubuntu-latest
    if: github.repository == 'numaproj-labs/numaplane'
    strategy:
      matrix:
        target: [ numaplane ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup Node-Cache
        uses: actions/cache@v4
        with:
          path: ui/node_modules
          key: ${{ runner.os }}-node-dep-v1-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Registry Login
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}

      - name: set Version
        id: version
        run: |
          tag=$(basename $GITHUB_REF)
          if [ $tag = "main" ]; then
            tag="latest"
          fi
          echo "::set-output name=VERSION::$tag"
      - name: Container build and push with arm64/amd64
        run: |
          IMAGE_NAMESPACE=${{ secrets.QUAYIO_ORG }} VERSION=${{ steps.version.outputs.VERSION }} DOCKER_PUSH=true make image

  Bom:
    runs-on: ubuntu-latest
    if: github.repository == 'numaproj-labs/numaplane'
    needs: [ build-push-linux-multi ]
    steps:
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      - run: |
          if [ ${GITHUB_REF##*/} = main ]; then
           echo "VERSION=latest" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
      - uses: actions/setup-go@v3.1.0
        with:
          go-version: '1.21'
      - uses: actions/checkout@v4
      - run: go install sigs.k8s.io/bom/cmd/bom@v0.2.0
      - run: go install github.com/spdx/spdx-sbom-generator/cmd/generator@v0.0.13
      - run: generator -o /tmp -p .
      - run: bom generate --image quay.io/numaio/numaplane-controller:$VERSION -o /tmp/numaplane-controller.spdx
      # pack the boms into one file to make it easy to download
      - run: cd /tmp && tar -zcf sbom.tar.gz *.spdx
      - uses: actions/upload-artifact@v3
        with:
          name: sbom.tar.gz
          path: /tmp/sbom.tar.gz

  Release:
    runs-on: ubuntu-latest
    if: github.repository == 'numaproj-labs/numaplane'
    needs: [ build-push-linux-multi, bom ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Version
        run: |
          if [ ${GITHUB_REF##*/} = main ]; then
            echo "VERSION=latest" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi
      - uses: actions/download-artifact@v3
        with:
          name: sbom.tar.gz
          path: /tmp
      - name: Registry Login
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
      - name: Release binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            manifests/*.yaml
            /tmp/sbom.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}